### ISSUE TITLE
Does not work on station NL54004.

### ISSUE THREAD

**Issue by bouwew** [metbril/pyluchtmeetnet#16]
**Describe the bug**
When using pyluchtmeetnet to obtain the data from my location, connecting to station NL54004, I receive an error.

When debugging your code, I can see that this station provides data on the following components: ['FN', 'NO', 'NO2', 'PM10']
But when collecting the related data, only data for FN and PM10 are returned.

Your present code:
```
        data = []
        for component in components:
            json_component = [
                meas for meas in measurements if meas["formula"] == component
            ]
            element = {
                component: json_component[0]["value"],
                "timestamp": json_component[0]["timestamp_measured"],
            }
            data.append(element)
```
fails on this returned data.

When I change to code to this:
```
        data = []  
        for component in components:
            for meas in measurements:
                if meas["formula"] == component:
                    json_component = [meas]
                    element = {
                        component: json_component[0]["value"],
                        "timestamp": json_component[0]["timestamp_measured"],
                    }
                    data.append(element)
```
it works on the returned data.

**Comment by metbril** [comment]
Thank you. I will have a look.

**Comment by metbril** [comment]
Thank you for reporting. While debugging, I've noticed that the `get_latest_station_measurements` method returns all available measurements for a component. I should only have reported the latest of each component. I will also make an adjustment for that.
